### ISSUE TITLE
IE11 is an outdated, obsolete browser; please replace with Edge instead

### ISSUE THREAD

**Issue by JohnWeisz** [burocratik/outdated-browser#270] opened 2017-06-03 11:33 UTC
We really appreciate the time and effort you put into this beautiful project folks, and would like to use it to suggest users to update their browsers.

However, suggesting users to "update" to IE11 is simply a big no. It's not a modern browser, it's an outdated one made obsolete by Edge. IE11 does not support many modern technologies a web application will likely depend on, and is not a valid choice for a modern browsing experience.

Please replace with Edge instead if you have a little time.

**Comment by swillis93** [comment] 2017-06-12 09:19
It depends on operating systems. Users with ie8 or 9 are likely to be running on Windows 7 or below, and as far as I'm aware, Edge will only work on Windows 10. This means it's pretty much impossible to do what you're asking.

Besides, [ie11 has almost 14% of the market share](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0), which I would argue is enough to require support, but obviously this is entirely project dependant.

**Comment by adamn** [comment] 2017-06-23 19:06
This is a duplicate of #268.

@swillis93 While you're right, the purpose of this project is for those deploying sites that require newer browser to have a simple and best practices solution to offer their users.  Since modern sites are beginning to no longer work on IE11 at all (our application [Factr](https://factr.com) for instance), we can't use this project.  

We would like to use the project.

Anyway, IE11 users don't have to be prompted to update their browser - we just need the destination page to not offer IE11 as a 'modern browser' to download.

**Comment by lentemarton** [comment] 2017-06-24 09:46
It's no question that IE is seriously out of date. Primary the lack of CSS custom properties, and CSS calc function makes it unsuitable for modern websites.

At least, it'd be nice to be able to target browsers that don't support the above, and suggest to use Edge instead of IE.

I'd love to see this feature implemented, as only this'd make this great product able to manage all old-browser-issues.

**Comment by JohnWeisz** [comment] 2017-06-24 10:46
@swillis93 

 > "Users with ie8 or 9 are likely to be running on Windows 7 or below, and as far as I'm aware, Edge will only work on Windows 10. This means it's pretty much impossible to do what you're asking."

I respectfully disagree that this would be a problem. Users will still have several options too choose from for Windows 7 and below, while users preferring Microsoft products using Windows 10 can still use Edge.

You need to consider this from a usability point of view: this project would be essentially (only?) useful for enabling web frontends to use modern technologies without having to keep considering completely obsolete browsers, including IE11, while offering users an elegant and trustworthy guide to get their way around. As things stand, we'll simply create our own guide for users, because the presence IE11 renders this project useless from our perspective.

 > "Besides, ie11 has almost 14% of the market share, which I would argue is enough to require support, but obviously this is entirely project dependant."

I certainly don't intend this to sound harsh, but let me get this clear: what you are considering is completely irrelevant from the perspective of a system. Simply put, I don't care if an obsolete browser has a 14% market share if that obsolete browser will simply never run my application (especially when users have several alternatives).

This is not a matter of business decisionmaking when you require technologies that are simply non-existent on some platforms.

**Comment by brunoamorim** [comment] 2017-06-26 13:28
@JohnWeisz, @swillis93 and @lentemarton thanks for your input guys. In fact we are working on a solution and soon we'll make available for everyone. The solution is for users that access to Outdated Browser website with IE below version 11, it will suggest the download the IE11. If anyone access with IE11 it will suggest to download Edge. Thanks.

**Comment by swillis93** [comment] 2017-06-26 13:39
@brunoamorim Yes this sounds like a good solution. Better to offer the correct browsers to people rather than offering them browsers that simply won't work on their system.

**Comment by Kum0ri** [comment] 2017-06-30 17:49
Hi ppl, edge/ie is a sensitive issue. We updated the website, for what we think is the best compromise. For the users that land in http://outdatedbrowser.com with IE10 browser or less, the website will suggest the latest Microsoft website that this user can download ( IE11 ), for users that land with IE11 the website will suggest that they download Windows 10 to use Microsoft Edge, since that's the only way that they have to update to the latest Microsoft browser, that is not IE11. For every other browser the website will suggest always the latest Microsoft browser ( Edge ).

Cheers!

**Closed by Kum0ri** 2017-06-30 17:49 UTC
